image: debian:latest

stages:
  - setup
  - lint
  - build
  - test

before_script:
  - apt-get update
  - apt-get install -y gcc make valgrind clang-format
  - gcc --version
  - make --version
  - valgrind --version
  - clang-format --version

setup_job:
  stage: setup
  script:
    - echo "Setup completed"

clang_format_job:
  stage: lint
  script:
    - unformatted_count=$(find . -iname "*.h" -o -iname "*.c" | xargs clang-format -style=file -output-replacements-xml | grep -c "<replacement ")
    - echo "Unformatted files count: $unformatted_count"
    - if [ $unformatted_count -ne 0 ]; then exit 1; fi
  only:
    - branches
    - merge_requests

build_job:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - ./bin/
      - ./obj/
  only:
    - branches
    - merge_requests

test_job:
  stage: test
  script:
    - make test
  artifacts:
    when: always
    paths:
      - ./bin/
      - ./obj/
  only:
    - branches
    - merge_requests
