image: debian:latest

stages:
  - setup
  - build
  - test
  - check-format
  - jalon1

before_script:
  - apt-get update
  - apt-get install -y git gcc make valgrind clang-format libreadline-dev
  - git --version
  - gcc --version
  - make --version
  - valgrind --version
  - clang-format --version

setup_job:
  stage: setup
  script:
    - echo "Setup completed"

build_job:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - ./bin/
      - ./obj/
  only:
    - branches
    - merge_requests

test_job:
  stage: test
  script:
    - make test
  artifacts:
    when: always
    paths:
      - ./bin/
      - ./obj/
  only:
    - branches
    - merge_requests

check_format_job:
  stage: check-format
  script:
    - make check-format
  only:
    - branches
    - merge_requests
  
test_jalon_1:
  stage: jalon1
  script:
    - ./Projet_test.sh
  only:
    - branches
    - merge_requests