image: debian:latest

stages:
  - setup
  - build
  - test
  - format_check

before_script:
  - apt-get update
  - apt-get install -y gcc make valgrind clang-format

setup_job:
  stage: setup
  script:
    - gcc --version
    - make --version
    - valgrind --version
    - clang-format --version
  only:
    - branches
    - merge_requests

build_job:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - ./bin/
      - ./obj/
  only:
    - branches
    - merge_requests

test_job:
  stage: test
  script:
    - make test
  artifacts:
    when: always
    paths:
      - ./bin/
      - ./obj/
  only:
    - branches
    - merge_requests

format_check_job:
  stage: format_check
  script:
    - find . -iname *.h -o -iname *.cpp | xargs clang-format -style=file -output-replacements-xml | grep "<replacement " >/dev/null
    - if [ $? -ne 1 ]; then echo "Code style issues found"; exit 1; fi
  only:
    - branches
    - merge_requests
