name: Job-Control-Shell-Emulator

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update packages
        run: sudo apt-get update
      
      - name: Install dependencies
        run: |
            sudo apt-get install -y gcc make
            gcc --version
            make --version

      - name: Build project
        run: make

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            ./bin/
            ./obj/
  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update packages
        run: sudo apt-get update
      
      - name: Install dependencies
        run: |
            sudo apt-get install -y gcc make valgrind
            gcc --version
            make --version
            valgrind --version

      - name: Run tests
        run: make test

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-artifacts
          path: |
            ./bin/
            ./obj/
  
  check-format:
    name: Check Format
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update packages
        run: sudo apt-get update
      
      - name: Install dependencies
        run: |
            sudo apt-get install -y make clang-format
            make --version
            clang-format --version
          
      - name: Check code format
        run: make check-format

  milestone1:
    name: Milestone 1
    needs: check-format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update packages
        run: sudo apt-get update
        
      - name: Install dependencies
        run: |
            sudo apt-get install -y git gcc make valgrind libreadline-dev
            git --version
            gcc --version
            make --version
            valgrind --version

      - name: Run Milestone 1 tests
        run: ./Projet_test.sh
